name: Deploy

on:
  push:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install Hal9
      run: pip install hal9
    - name: Deploy App
      run: hal9 deploy echo --name ECHO
      env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}
